---
title: "Exercise-02b Notes"
author: "Stephen Collins"
output: html_document
date: "1.25.2025 - `r format(Sys.time(), '%m.%d.%Y')`"
---
Side note: 

- I started to add a author line
- I added the date for when the doc was created but then I added a code for when it is last edited. 
- A question I have is whether or not I can have this pop up every time on its own or do I have 
to manually do this every time??

# Titles: Less Number Signs Means Larger Title
## Titles: 
### Titles: 
#### Titles: More Number Signs Means Smaller Title


# Thoughts on creating Repositories 
- It's definitely way easier to just create the depository in Github first and then adding to RStudio first versus doing it the other way around. 
- I can **NOT** get the *usethis::use_github(protocol="https")* code to work. 
- I keep getting an error saying "*Can't find any local branches.Do you need to make your first commit?*"
- If I just add a branch then its like completing Connecting a Local Repo to GitHub: Option 2


